version: '3'
services:  
# ---------- MariaDB-Docker ----------
    mariadb:
      container_name: mariaDB
      build:
        context: ./mariaDB
        dockerfile: dev.dockerfile
      environment:
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=userDB
      ports:
        - "3306:3306"
      restart: 'always'
# ---------- UI-Docker ---------- 
    UI:
      image: node:16
      container_name: UI
      build:
        context: ./UI
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      restart: always